# A helper script to populate vtable in _MCIL_SERVICE_CALLBACKS
# @author Nyan Cat
# @category A_Red
# @keybinding
# @menupath
# @toolbar

# pyright: reportMissingImports=false
# pyright: reportUndefinedVariable=false

from java.util import ArrayList

from ghidra.program.model.data import CategoryPath, FunctionDefinitionDataType, PointerDataType
from ghidra.program.model.data import DataTypeConflictHandler


def getDataType(typeName, typeManager):
    matches = ArrayList()
    typeManager.findDataTypes(typeName, matches)

    if len(matches) > 1:
        print("Warning: Using the first " + typeName)
    elif len(matches) == 0:
        return None

    return matches[0]


funcManager = currentProgram.getFunctionManager()
typeManager = currentProgram.getDataTypeManager()

funcNames = ['getPciConfigData', 'setPciConfigData', 'getPciConfigData', 'setPciConfigData', 'readRomImage', 'delayInMicroseconds', 'sleepInMilliseconds', 'getRegistryKey', 'setRegistryKey', 'syncExecution', 'allocateMemory', 'releaseMemory', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'waitForGUIIdle', 'waitForMCIdle', 'executeBiosTable', 'queryTableRevision', 'querySystemInfo', 'isAsicCapEnabled', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'copyMemory', 'zeroMemory', 'setMessageCode', 'modifyRegister', 'notifyEvent', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'eRecordSystemAccess', 'eRecordErrorMessage', 'assertInterrupt', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'waitFor', 'dummyCallBack', 'dummyCallBack', 'obtainIri', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', None, 'dummyCallBack', 'systemTimestamp', 'dummyCallBack', None, None, None, None, None, None, None, None, 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack', 'gpuPowerControl', 'dummyCallBack', 'dummyCallBack', 'dummyCallBack']
# funcNames = ["AtiAppleCailServices::" + x for x in funcNames]
done = [False] * len(funcNames)
ptrs = [None] * len(funcNames)

for func in funcManager.getFunctions(True):
    fullName = str(func)
    funcName = fullName.split("::")[-1]
    if funcName not in funcNames:
        continue

    funcSign = func.getSignature(False)

    funcType = FunctionDefinitionDataType(CategoryPath("/AMDGen/FuncSigns"), funcName + "_sign", funcSign)
    funcType = typeManager.addDataType(funcType, DataTypeConflictHandler.REPLACE_HANDLER)
    ptrType = PointerDataType(funcType, typeManager)
    ptrType = typeManager.addDataType(ptrType, DataTypeConflictHandler.REPLACE_HANDLER)

    for i in range(len(funcNames)):
        if funcNames[i] == funcName:
            assert not done[i]
            done[i] = True
            ptrs[i] = ptrType
            funcNames[i] = fullName

assert all([done[i] or funcNames[i] is None for i in range(len(funcNames))])

serviceCallback = getDataType("_MCIL_SERVICE_CALLBACKS", typeManager)
for i in range(len(funcNames)):
    if funcNames[i] is None:
        continue
    serviceCallback.replaceAtOffset(8 * (i + 2), ptrs[i], 8, funcNames[i], "Generated by Z_createMcilServiceCallbackVtable.py")
